# Metrics Server configuration for AKS
# --kubelet-insecure-tls is required for AKS clusters
metrics-server:
  replicas: 2
  namespaceOverride: control-plane-system
  args:
    - --kubelet-insecure-tls
