apiVersion: v2
name: crossplane
description: Managed Resources addon for the control plane cluster

type: application

version: 0.1.0

appVersion: "1.0.0"

keywords:
  - crossplane
  - managed resources
  - resources system

dependencies:
  - name: crossplane
    # version: 1.18.2
    version: 2.1.3
    repository: https://charts.crossplane.io/stable/
