cluster: algo-trading-plat
template:
  name: data-plane-template
provisioner:
  name: data-plane-provisioner
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["arm64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t4g.small"]
  limits:
    resources:
      cpu: 20
      memory: 40Gi
  ttlSecondsAfterEmpty: 10